### ISSUE TITLE
[1주차] 업무에 바로 쓰는 SQL 튜닝_1장_이준렬

### ISSUE THREAD

**Issue by lee-JunR** [2024-BookStudy/bookmark#73]
## 이슈 1. 마스터 슬레이브 패턴?
저는 오라클 db 와 MySQL 의 구조적 차이를 설명하면서 마스터 슬레이브 패턴의 예시를 들었는데 해당 부분이 잘 이해가 안갑니다!
스프링 애플리케이션이라면 
```
spring:
  datasource:
    master:
      url: jdbc:mysql://master-db-url:3306/mydb
      username: username
      password: password
    slave:
      url: jdbc:mysql://slave-db-url:3306/mydb
      username: username
      password: password
```
이런식으로 따로 2개의 DB를 만들어 진행해서 읽기 작업과 쓰기 작업의 차이를 둔다는 것 맞나요?
슬레이브 DB는 마스터 DB 의 데이터를 복제해서 최신상태를 계속 유지한다는 거라고 이해했습니다.
